cal/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    # url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    url(r'^event/delete/(?P<event_id>\d+)/$', views.event_del, name='event_del'),
    url(r'^data_is_here/$', views.data_is_here, name='data_is_here'),
]

djangoCalender/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cal.urls')),
]

cal/models.py
from django.db import models
from django.urls import reverse

Labs = [('nab0101','NAB 0101'),
        ('nab0103','NAB 0103'),
        ('nab0104', 'NAB 0104'),
        ('nab0105', 'NAB 0105'),
        ('nab0106', 'NAB 0106'),
        ('nab0109', 'NAB 0109'),
        ('nab0111', 'NAB 0111'),
        ('nab0113', 'NAB 0113'),
        ('nab0117', 'NAB 0117'),
        ('nab3104', 'NAB 3104'),
        ('studn3326', 'STUDN 3326'),]

class Event(models.Model):
    my_id = models.AutoField(primary_key = True)
    title = models.CharField(max_length=100)
    room_number = models.CharField(max_length=10, choices=Labs, default='nab0101')
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.id = None

    @property
    def get_html_url(self):
         url = reverse('cal:event_edit', args=(self.id,))
        # return f'<a href="{url}"> {self.title} </a>'

    def __str__(self):
        return 'my_id: {}\ntitle: {}\nroom_number: {}\nstart_time: {}\nend_time: {}'.format(
            self.my_id, self.title, self.room_number, self.start_time, self.end_time)

cal/forms.py
from django.forms import ModelForm, DateInput, forms, DateField
from cal.models import Event
import datetime
from django.forms import SelectDateWidget


class EventForm(ModelForm):
    class Meta:
        model = Event
        # datetime-local is a HTML5 input type, format to make date time show on fields
        # start_time = forms.DateTimeField(input_formats=['%Y-%m-%dT%H:%M'],widget=forms.DateTimeInput( attrs={'type': 'datetime-local','class': 'form-control'},format='%Y-%m-%dT%H:%M'))
        # end_time = forms.DateTimeField(input_formats=['%Y-%m-%dT%H:%M'],widget=forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'},format='%Y-%m-%dT%H:%M'))
        widgets = {
            'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        # widgets ={
        #     'date_for_lab': DateInput(attrs={'class':'datepicker'}, format='%Y/%m/%d'),
        #     'start_time': DateInput(attrs={'class':'timepicker'}, format='%H:%i:%A'),
        #     'end_time': DateInput(attrs={'class': 'timepicker'}, format='%H:%i:%A')
        # }
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        # input_formats to parse HTML5 datetime-local input to datetime field
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

cal/views.py
import json
from datetime import datetime, timedelta, date

from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.contrib import messages
from django.utils.safestring import mark_safe
import calendar

from .models import *
from .utils import Calendar
from .forms import EventForm


def index(request):
    return HttpResponse('hello')


class CalendarView(generic.ListView):
    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)


def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        if is_overlapping(form.instance.room_number, form.instance.start_time, form.instance.end_time):
            # There is a overlap. Show an error.
            messages.error(request, 'Conflicting timing. Please select another time.')
            return render(request, 'cal/event.html', {'form': form})
        else:
            form.save()
            return HttpResponseRedirect(reverse('cal:data_is_here'))
    return render(request, 'cal/event.html', {'form': form})


def event_del(request, event_id):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
        instance.delete()
    return HttpResponseRedirect(reverse('cal:data_is_here'))


def is_overlapping(room_number, start_time, end_time):  # start_time 1 PM, End-time = 2PM
    events = Event.objects.filter(room_number=room_number)  # Get all the registered events.
    for event in events:
        print('event_room_number', event.room_number)
        print('event_start_time', event.start_time)
        print('event_end_time', event.end_time)
        # Loop through registered events to find out overlap.
        if event.start_time >= end_time:
            # If current event starts after user requested start time, then there is no overlap.
            print('First valid', str(event))
            continue
        elif event.end_time <= start_time:
            # If current event ends before user requested time, then there is no overlap.
            print('second valid', str(event))
            continue
        else:
            # There is a possibility for overlapping.
            print('Overlapping Event=', str(event))
            return True
    return False


def data_is_here(request):
    data = Event.objects.all()
    events = []
    for e in data:
        events.append({
            'id': e.my_id,
            'title': e.title,
            'start': e.start_time.strftime('%Y-%m-%dT%H:%M'),
            'end': e.end_time.strftime('%Y-%m-%dT%H:%M')
        })
    return render(request, 'cal/calendar.html', {'data': events})

cal/templates/cal/base.html
{% load static %}

<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/new_style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/main.css' %}">
<!--  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>-->
  <script src="{% static 'cal/js/main.js' %}" type="text/javascript"></script>
  <script src='http://fullcalendar.io/js/fullcalendar-2.1.1/lib/jquery.min.js'></script>
  <script src="http://fullcalendar.io/js/fullcalendar-2.1.1/lib/jquery-ui.custom.min.js"></script>
  <script src='http://fullcalendar.io/js/fullcalendar-2.1.1/lib/moment.min.js'></script>
  <script src='http://fullcalendar.io/js/fullcalendar-2.1.1/fullcalendar.min.js'></script>
  <script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');
    const events = {{data|safe}};

    var calendar = new FullCalendar.Calendar(calendarEl, {
      height: '100%',
      expandRows: true,
      slotMinTime: '08:00',
      slotMaxTime: '20:00',
      headerToolbar: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
      },
      initialView: 'dayGridMonth',
      initialDate: '2020-05-12',
      navLinks: true, // can click day/week names to navigate views
      editable: true,
      selectable: true,
      nowIndicator: true,
      dayMaxEvents: true, // allow "more" link when too many events
      events: events,
      eventClick:function(event){
      if(event){
          var idEvent = event.event.id;
<!--          alert("you clicked:" + idEvent);-->
          window.location.href = "/event/edit/" + idEvent;
        }
      }
    });
    calendar.render();
  });

</script>

  <title>SUNY Lab Reservation</title>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <h1 class="title">{% block title %}{% endblock %}</h1>
      </div>
      <div class="col-12">
        <hr>
      </div>
    </div>

      {% block content %}
      {% endblock %}
  </div>
</body>
</html>

cal/templates/cal/calendar.html
{% extends 'cal/base.html' %}

{% block title %}LAB RESERVATION{% endblock %}
{% block content %}
<div class="row" style="height:100%">
  <div class="col-12" style="margin-left:13">
    <a class="btn btn-info left" href="{% url 'cal:event_new' %}"> Make Reservation </a>
  </div>
  <div class="col-12">
      <div id='calendar'></div>
  </div>
</div>


{% endblock %}

cal/templates/cal/event.html
{% extends 'cal/base.html' %}

{% block title %}
Reserve Lab
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:data_is_here' %}"> Calendar </a>
</div>

<div>
  {% if messages %}
    <ul style="height:0%">
      {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
</div>

<form method="post">

  {% csrf_token %}
  <table class="form form-table">
    {{ form }}

    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
    {% if form.instance.my_id %}
      <tr><td colspan= "2"> <a class="btn btn-info right" type="button" href="/event/delete/{{form.instance.my_id}}">Delete</a> </td></tr>
    {% endif %}
  </table>
</form>
{% endblock %}